export const PROFILE_ROUTE = "/profile"
export const LOGIN_ROUTE = "/login"
export const REGISTRATION_ROUTE = "/registration"
export const QUESTION_TASKS_ROUTE = "/task"
export const INDEX_ROUTE = "/tasks"
export const LOGIN_DONE_ROUTE = "/loginComplete"
export const ADMIN_PANEL = "/adminPanel"
export const CHECK_QUESTION_STUDENTS = "/CheckDoneQuestionsStudents"
export const LIST_STUDENTS = "/listStudents"
export const MAIN_PAGE = "/"
export const ABOUT_US_ROUTE = "/aboutUs"

export const ADMIN_ROLE = "ADMIN"
export const TEACHER_ROLE = "TEACHER"
export const STUDENT_ROLE = "STUDENT"